import PDFDocument from "pdfkit";

interface InvoicePdfInput {
  hospitalName: string;
  hospitalAddress?: string;
  invoiceNo: string;
  title: string;
  status: string;
  dueAt: Date;
  items: Array<{ description: string; quantity: string; unitPrice: string; vatAmount: string; lineTotal: string }>;
  subtotal: string;
  discountAmount: string;
  vatAmount: string;
  totalAmount: string;
  paidAmount: string;
  dueAmount: string;
}

function collect(document: PDFKit.PDFDocument) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    document.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", reject);
    document.end();
  });
}

export function createInvoicePdf(input: InvoicePdfInput) {
  const doc = new PDFDocument({ size: "A4", margin: 48, info: { Title: `Invoice ${input.invoiceNo}` } });
  doc.fontSize(19).fillColor("#17365d").text(input.hospitalName);
  if (input.hospitalAddress) doc.fontSize(9).fillColor("#526071").text(input.hospitalAddress);
  doc.moveDown(1.2).fontSize(24).fillColor("#111827").text("INVOICE", { align: "right" });
  doc.fontSize(10).text(`Invoice: ${input.invoiceNo}`, { align: "right" });
  doc.text(`Status: ${input.status}`, { align: "right" });
  doc.text(`Due: ${input.dueAt.toLocaleDateString("en-GB")}`, { align: "right" });
  doc.moveDown().fontSize(14).text(input.title);
  doc.moveDown();
  const widths = [225, 50, 70, 60, 94];
  const headers = ["Description", "Qty", "Unit", "VAT", "Total"];
  let x = 48; const y = doc.y;
  doc.rect(48, y - 5, 499, 24).fill("#e8eef7").fillColor("#172033").fontSize(9);
  headers.forEach((header, index) => { const width = widths[index]!; doc.text(header, x + 4, y + 2, { width: width - 8, align: index ? "right" : "left" }); x += width; });
  doc.y = y + 25;
  for (const item of input.items) {
    const rowY = doc.y; x = 48;
    const values = [item.description, item.quantity, item.unitPrice, item.vatAmount, item.lineTotal];
    values.forEach((value, index) => { const width = widths[index]!; doc.text(value, x + 4, rowY, { width: width - 8, align: index ? "right" : "left" }); x += width; });
    doc.moveDown(1.4).strokeColor("#e5e7eb").moveTo(48, doc.y).lineTo(547, doc.y).stroke();
  }
  doc.moveDown();
  const totals = [["Subtotal", input.subtotal], ["Discount", input.discountAmount], ["VAT", input.vatAmount], ["Total", input.totalAmount], ["Paid", input.paidAmount], ["Due", input.dueAmount]];
  totals.forEach(([label, value], index) => {
    doc.font(index >= 3 ? "Helvetica-Bold" : "Helvetica").text(`${label}: BDT ${value}`, 350, doc.y, { width: 197, align: "right" });
  });
  doc.moveDown(2).font("Helvetica").fontSize(8).fillColor("#667085").text("Generated by Hospital Billing SaaS. Amounts are calculated and stored by the server.", { align: "center" });
  return collect(doc);
}

export function createReceiptPdf(input: { hospitalName: string; transactionId: string; invoiceNo: string; amount: string; method: string; paidAt: Date }) {
  const doc = new PDFDocument({ size: "A5", margin: 44, info: { Title: `Receipt ${input.transactionId}` } });
  doc.fontSize(18).fillColor("#17365d").text(input.hospitalName, { align: "center" });
  doc.moveDown().fontSize(22).fillColor("#111827").text("PAYMENT RECEIPT", { align: "center" });
  doc.moveDown(1.5).fontSize(10);
  const details: Array<[string, string]> = [["Transaction", input.transactionId], ["Invoice", input.invoiceNo], ["Payment method", input.method], ["Paid at", input.paidAt.toLocaleString("en-GB")]];
  details.forEach(([label, value]) => {
    doc.fillColor("#667085").text(label); doc.fillColor("#111827").font("Helvetica-Bold").text(value).font("Helvetica").moveDown(0.5);
  });
  doc.moveDown().roundedRect(44, doc.y, 332, 65, 8).fill("#eaf6ee");
  doc.fillColor("#166534").fontSize(10).text("AMOUNT PAID", 60, doc.y + 15, { align: "center", width: 300 });
  doc.font("Helvetica-Bold").fontSize(21).text(`BDT ${input.amount}`, 60, doc.y + 3, { align: "center", width: 300 });
  doc.moveDown(5).font("Helvetica").fontSize(8).fillColor("#667085").text("This receipt represents a validated payment recorded by Hospital Billing SaaS.", { align: "center" });
  return collect(doc);
}
